sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: IPt9bdwK65yQwtN1bS3XP26RwggsNvwX8GNQwlROB3vExWbgAQzagIrfUBntvDBFGhEu9D7Dq/dzSY/6ffu0+Dcllrg1uSu3fyavDG2KTFNwljcLadPPBPDVZQy0RUCJTlgBtymNcOGMfUgulN+U2A9FgX9YOaWs1zlkFJ5d/KJgMr+PnnPmJjzlQLzy7TSllKRUMsvQD0n8eCePTbZebSetqKO52HNqizkfMfq3IJ8rj1uAQf1w0vXJj6oLaXZlUlqNj5GjY7ZICyT3U1L3rFg42ZH+vZ816Xz0YppdW3LCQVvGzwSbOn6wIT9wrFhrv/t2Jmq3uW6MD9N9Z1aMw8+7HabaCBT+dOnk+PHpx9eB8pzJgDqininHwAhMhr0UdzQRXoxxVOyRBzWdAnsH4nTJXz3Su6u75Bj0moKgW+stCIwbhXDM2svekwzajEbhFsDXrPuIZ+oXd7iUukINB3Wo5LIvLpHhHRl2Ghu7rgYCUXwTSDuSLOogc13govyBw4EzWVOGD/2wnyWYPSjHxbJd1pf6iVf1LJxnjw/Altvt+nubOvchlSkAlzeBIsWhVz1l3jf2RugGzLx5xsbOI/CWJ2dqgDwcn1zu79xB09y93PdGqHnl9ksOvh3t8g8qQnTxoXFJzqfbtzFN7U1jkcWDapWO6uB0eIqLvuTq1V4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Andersonville--A-Story-of-Rebel-Military-Prisons---Volume-4_4260
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy